/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Bean.Categoria;
import javax.swing.DefaultListModel;
import Controladores.*;
import Estructuras.ArbolB;
import Estructuras.NodoLibro;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gerso
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    String ip;
    String puerto;
    ContCategoria cg;
    DefaultListModel modeloLista;
    DefaultTableModel modeloTabla;

    public Principal() {

        initComponents();
        cg = new ContCategoria();
        modeloLista = new DefaultListModel();
        modeloTabla = new DefaultTableModel();
        lista.setModel(modeloLista);
        tabla.setModel(modeloTabla);
        modeloTabla.addColumn("ISBN");
        modeloTabla.addColumn("Titulo");
        modeloTabla.addColumn("Categoria");
        modeloTabla.addColumn("Autor");
        modeloTabla.addColumn("Edicion");
        modeloTabla.addColumn("Año");
        modeloTabla.addColumn("Idioma");
        modeloTabla.addColumn("Carnet");

        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPuertoIp = new javax.swing.JTextArea();
        btnDatosConexion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        btnEliminarCategoria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarCategoria = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblLibros = new javax.swing.JLabel();
        btnAgregarLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        txtEliminar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEliminarNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnCerrar = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btnPuertoIp = new javax.swing.JMenuItem();
        btnReportes = new javax.swing.JMenu();
        btnUsuarios = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Biblioteca");

        txtPuertoIp.setColumns(20);
        txtPuertoIp.setRows(5);
        jScrollPane2.setViewportView(txtPuertoIp);

        btnDatosConexion.setText("Datos de conexión");
        btnDatosConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosConexionActionPerformed(evt);
            }
        });

        lista.setToolTipText("");
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lista);

        btnEliminarCategoria.setText("Eliminar");
        btnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategoriaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Categorias: ");

        btnAgregarCategoria.setText("Agregar");
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Titulo", "Categoría", "Autor", "Edición", "Año", "Idioma", "Carnet"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        lblLibros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLibros.setText("Libros: ");

        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnEliminarLibro.setText("Eliminar Libro");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });

        jLabel3.setText("ISBN");

        jLabel4.setText("Nombre");

        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnCerrar);

        jMenu2.setText("Configuracion");

        btnPuertoIp.setText("Establecer puerto y direccion IP");
        btnPuertoIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuertoIpActionPerformed(evt);
            }
        });
        jMenu2.add(btnPuertoIp);

        jMenuBar1.add(jMenu2);

        btnReportes.setText("Reportes");
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnReportes);

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnDatosConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnEliminarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLibros)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEliminar)
                                        .addComponent(btnEliminarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtEliminarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnAgregarCategoria)
                            .addComponent(lblLibros)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEliminarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDatosConexion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
PuertoIp ipp = new PuertoIp();
    private void btnPuertoIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuertoIpActionPerformed
        // TODO add your handling code here:

        ipp.setVisible(true);
        ipp.setLocationRelativeTo(null);


    }//GEN-LAST:event_btnPuertoIpActionPerformed

    private void btnDatosConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosConexionActionPerformed
        // TODO add your handling code here:
        puerto = ipp.getPuerto();
        ip = ipp.getIp();
        txtPuertoIp.setText("IP: " + ip + " \nPuerto: " + puerto);
    }//GEN-LAST:event_btnDatosConexionActionPerformed

    private void btnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategoriaActionPerformed
        // TODO add your handling code here:
        cg.getCategorias().eliminar(lista.getSelectedValue(), cg.getCategorias().getRaiz());
        actualizarLista();
        //  actualizarTabla();

    }//GEN-LAST:event_btnEliminarCategoriaActionPerformed

    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
        // TODO add your handling code here:
        ArbolB nuevo = new ArbolB();
        cg.getCategorias().crearCategoria(txtCategoria.getText(), nuevo);
        actualizarLista();

    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        IngresarLibros il = new IngresarLibros();
        this.setVisible(false);
        il.setVisible(true);
        il.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        // TODO add your handling code here:

        if (lista.getSelectedValue() != null) {
            lblLibros.setText("Libros de: " + lista.getSelectedValue());
            actualizarTabla();
        }


    }//GEN-LAST:event_listaMouseClicked

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:

        if (txtEliminar.getText().equals("") && txtEliminarNombre.getText().equals("")) {
            Categoria c = cg.getCategorias().buscar(modeloTabla.getValueAt(tabla.getSelectedRow(), 2).toString());

            c.getLibros().eliminar2(Integer.parseInt(modeloTabla.getValueAt(tabla.getSelectedRow(), 0).toString()));
            actualizarTabla();
        } else if (!txtEliminar.getText().equals("")) {
            eliminarLibroISBN(cg.getCategorias().getRaiz(), Integer.parseInt(txtEliminar.getText()));
            actualizarTabla();
        } else if(txtEliminar.getText().equals("")&&!txtEliminarNombre.getText().equals("")){
              eliminarLibroNombre(cg.getCategorias().getRaiz(), txtEliminarNombre.getText());
            actualizarTabla();
        }


    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        // TODO add your handling code here:
        Reportes r = new Reportes();
        r.setVisible(true);
        this.setVisible(false);
        r.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnReportesMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
        l.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        // TODO add your handling code here:
        UsuariosV u = new UsuariosV();
        this.setVisible(false);
        u.setVisible(true);
        u.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_btnUsuariosMouseClicked

    public void actualizarTabla() {
        modeloTabla.setRowCount(0);

        if (lista.getSelectedValue().equals("todo")) {
            llenarTablaAVL(cg.getCategorias().getRaiz());
        } else {
            Categoria c = cg.getCategorias().buscar(lista.getSelectedValue());
            if (!c.getLibros().isEmpty()) {
                llenarTabla(c.getLibros().getRaiz());
            }
        }

    }

    public void eliminarLibroISBN(Categoria aux, int isbn) {
        if (aux != null) {
            aux.getLibros().eliminar2(isbn);
            eliminarLibroISBN(aux.getIzquierda(), isbn);
            eliminarLibroISBN(aux.getDerecha(), isbn);
        }
    }

    public void eliminarLibroNombre(Categoria aux, String nombre) {
        if (aux != null) {
            aux.getLibros().eliminarPorNombre(nombre);
            eliminarLibroNombre(aux.getIzquierda(), nombre);
            eliminarLibroNombre(aux.getDerecha(), nombre);
        }
    }

    public void llenarTablaAVL(Categoria aux) {

        if (aux != null) {
            llenarTabla(aux.getLibros().getRaiz());
            llenarTablaAVL(aux.getIzquierda());
            llenarTablaAVL(aux.getDerecha());

        }
    }

    public void llenarTabla(NodoLibro nl) {

        Object[] fila;
        if (nl != null) {
            System.out.println();
            for (int i = 0; i < nl.getLibros().length; i++) {
                if (nl.getLibros()[i] != null) {
                    System.out.println(nl.getLibros()[i].getISBN());

                    fila = new Object[8];
                    fila[0] = nl.getLibros()[i].getISBN();
                    fila[1] = nl.getLibros()[i].getTitulo();
                    fila[2] = nl.getLibros()[i].getCategoria();
                    fila[3] = nl.getLibros()[i].getAutor();
                    fila[4] = nl.getLibros()[i].getEdicion();
                    fila[5] = nl.getLibros()[i].getAño();
                    fila[6] = nl.getLibros()[i].getIdioma();
                    fila[7] = nl.getLibros()[i].getCarnet();

                    modeloTabla.addRow(fila);

                    llenarTabla(nl.getLibros()[i].getIzquierda());

                } else {
                    llenarTabla(nl.getLibros()[i - 1].getDerecha());
                    break;
                }

            }

            // System.out.println(nl.getLibros()[nl.getLibros().length-1].getISBN() + " " + nl.getLibros()[nl.getLibros().length-1].getTitulo());
        }
    }

    public void actualizarLista() {
        modeloLista.clear();
        modeloLista.addElement("todo");
        llenarLista(cg.getCategorias().getRaiz());
    }

    public void llenarLista(Categoria aux) {

        if (aux != null) {
            modeloLista.addElement(aux.getNombre());
            llenarLista(aux.getIzquierda());
            llenarLista(aux.getDerecha());

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JMenu btnCerrar;
    private javax.swing.JButton btnDatosConexion;
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JMenuItem btnPuertoIp;
    private javax.swing.JMenu btnReportes;
    private javax.swing.JMenu btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLibros;
    private javax.swing.JList<String> lista;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtEliminarNombre;
    private javax.swing.JTextArea txtPuertoIp;
    // End of variables declaration//GEN-END:variables
}
